[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["Sandesh Devaraju <scouredimage@gmail.com>"]

[tool.poetry.dependencies]
python = "3.6"
requests = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
